const firstWhatNames = [
    ["cats.html", "A Page Dedicated to Cats"],
    ["cats2.html", "Another Page Dedicated to Cats"],
    ["coffee-shop.html", "Camper Cafe"],
    ["markers.html", "CSS Color Markers"],
    ["form.html", "A pretty HTML Form"],
    ["rothko.html", "Rothko Painting Creation"],
    ["nutrition-label.html", "US Nutrition Label"],
    ["accessible-quiz.html", "Accessible Quiz"],
    ["balance-sheet.html", "A Balance Sheet"],
    ["picasso.html", "A Picasso-Inspired Painting"],
    ["piano.html", "freeCodeCamp Piano"],
    ["city.html", "City... Resize to see day to night"],
    ["magazine.html", "Bored? Read a freeCodeCamp Magazine"],
    ["ferris-wheel.html", "A Fun Ferris Wheel Animation"],
    ["penguin.html", "Penguin Animation"],
];